import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {Text, Grid} from '@nextui-org/react';
import {LinkCard} from '../components/link';
import { faCodeBranch } from '@fortawesome/free-solid-svg-icons'
import { faUserTie } from '@fortawesome/free-solid-svg-icons'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Fred Davison</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Text h1
                      css={{
                          lineHeight: '80px',
                          '@xs': {
                              fontSize: '85px'
                          },
                          '@xl': {
                              fontSize: '105px'
                          }
                      }}
                >
                    Fred Davison
                </Text>
                <Text h2 css={{
                    '@xs': {
                        fontSize: '55px'
                    },
                    '@xl': {
                        fontSize: '75px'
                    }
                }}
                >full-stack developer</Text>
                <Grid.Container gap={2} justify='center' direction='column'
                                css={{
                                    alignItems: 'center',
                                    '@xs': {
                                        fd: 'row',
                                        m: '0 auto',
                                    }
                                }}>
                    <Grid xs={4} sm={2} justify='center'>
                        {LinkCard('GitHub', 'https://github.com/crochetcode', faCodeBranch)}
                    </Grid>
                    <Grid xs={4} sm={2} justify='center'>
                        {LinkCard('LinkedIn', 'https://www.linkedin.com/in/fdavison1', faUserTie)}
                    </Grid>
                </Grid.Container>
            </main>
        </div>
    );
}
