import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {Text, Grid, Card} from '@nextui-org/react';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Fred Davison | developer</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className={styles.main}>
                <Text h1 size={85} css={{lineHeight: '80px'}}>Fred Davison</Text>
                <Text h2 size={55}
                     >full-stack developer</Text>
                <Grid.Container gap={2} justify="center">
                    <Grid xs={2}>
                        <Card
                            isPressable
                            isHoverable
                            variant="bordered"
                            css={{ mw: "400px"}}
                        >
                            <Card.Body css={{textAlign: 'center'}}>
                                <Text size='$3xl'>GitHub</Text>
                            </Card.Body>
                        </Card>
                    </Grid>
                    <Grid xs={2}>
                        <Card
                            isPressable
                            isHoverable
                            variant="bordered"
                            css={{ mw: "400px" }}
                            color='gradient'
                        >
                            <Card.Body>
                                <Text size='$3xl' css={{textAlign: 'center'}}>LinkedIn</Text>
                            </Card.Body>
                        </Card>
                    </Grid>
                </Grid.Container>
            </main>
        </div>
    );
}
